# Generated by Django 2.0.1 on 2018-03-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_symbol', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=40)),
                ('company_last_sale', models.CharField(max_length=10)),
                ('company_market_cap', models.CharField(max_length=10)),
                ('company_ipo_year', models.CharField(max_length=5)),
                ('company_sector', models.CharField(max_length=20)),
                ('company_industry', models.CharField(max_length=60)),
                ('comany_summary_quote', models.CharField(max_length=60)),
            ],
        ),
    ]
