# Generated by Django 2.0.1 on 2018-04-07 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0002_orders_track'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
