# Generated by Django 2.0.1 on 2018-04-07 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0003_auto_20180407_2038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
