# Generated by Django 2.0.1 on 2018-04-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0004_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('bs', models.CharField(max_length=4)),
                ('sname', models.CharField(max_length=50)),
                ('sprice', models.CharField(max_length=10)),
                ('squantity', models.CharField(max_length=20)),
                ('ssymbol', models.CharField(max_length=8)),
                ('total_worth', models.CharField(max_length=25)),
            ],
        ),
    ]
